# sites that hosts regional contests
- name: University of Alberta
  location: Edmonton, Alberta
  url: https://rocky.icpc.io/alberta

- name: Montana Tech
  location: Butte, Montana
  url: https://rocky.icpc.io/mtech

- name: Brigham Young University
  location: Provo, Utah
  url: https://rocky.icpc.io/byu

- name: Colorado School of Mines
  location: Golden, Colorado
  url: https://rocky.icpc.io/mines
